pageInfo:
  title: TenSaaS Multiempresa Portal
  description: Estado Global de la Infraestructura
appConfig:
  theme: nord
  layout: auto
sections:
- name: 🛠️ Infraestructura Global
  items:
  - title: Admin Panel
    icon: fas fa-user-shield
    url: http://localhost:8000
    statusCheck: true
  - title: Grafana
    icon: si-grafana
    url: http://localhost:3000
    statusCheck: true
  - title: Portainer
    icon: si-portainer
    url: http://localhost:9000
    statusCheck: true
- name: 🥐 Servicios Cliente: Panaderia
  items:
  - title: MariaDB
    icon: si-mariadb
    url: http://localhost:8100
    statusCheck: true
  - title: WordPress
    icon: si-wordpress
    url: http://localhost:8101
    statusCheck: true
