global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: '7445586884:AAH9f7f89880e9e209e8c5fc4e3cd90518b'
    chat_id: -5274755868
    send_resolved: true
    parse_mode: 'HTML'
    message: |
      <b>🔔 Alerta del Sistema SaaS</b>
      <b>Estado:</b> {{ .Status }}
      {{ range .Alerts }}
      <b>Alerta:</b> {{ .Labels.alertname }}
      <b>Severidad:</b> {{ .Labels.severity }}
      <b>Descripción:</b> {{ .Annotations.description }}
      <b>Iniciado:</b> {{ .StartsAt.Format "15:04:05" }}
      {{ end }}
